/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FichesTangenteRouteImport } from './routes/fiches.tangente'
import { Route as FichesPemdasRouteImport } from './routes/fiches.pemdas'
import { Route as FichesLogiqueBooleenneRouteImport } from './routes/fiches.logique-booleenne'
import { Route as FichesSlugRouteImport } from './routes/fiches.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FichesTangenteRoute = FichesTangenteRouteImport.update({
  id: '/fiches/tangente',
  path: '/fiches/tangente',
  getParentRoute: () => rootRouteImport,
} as any)
const FichesPemdasRoute = FichesPemdasRouteImport.update({
  id: '/fiches/pemdas',
  path: '/fiches/pemdas',
  getParentRoute: () => rootRouteImport,
} as any)
const FichesLogiqueBooleenneRoute = FichesLogiqueBooleenneRouteImport.update({
  id: '/fiches/logique-booleenne',
  path: '/fiches/logique-booleenne',
  getParentRoute: () => rootRouteImport,
} as any)
const FichesSlugRoute = FichesSlugRouteImport.update({
  id: '/fiches/$slug',
  path: '/fiches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fiches/$slug': typeof FichesSlugRoute
  '/fiches/logique-booleenne': typeof FichesLogiqueBooleenneRoute
  '/fiches/pemdas': typeof FichesPemdasRoute
  '/fiches/tangente': typeof FichesTangenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fiches/$slug': typeof FichesSlugRoute
  '/fiches/logique-booleenne': typeof FichesLogiqueBooleenneRoute
  '/fiches/pemdas': typeof FichesPemdasRoute
  '/fiches/tangente': typeof FichesTangenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fiches/$slug': typeof FichesSlugRoute
  '/fiches/logique-booleenne': typeof FichesLogiqueBooleenneRoute
  '/fiches/pemdas': typeof FichesPemdasRoute
  '/fiches/tangente': typeof FichesTangenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fiches/$slug'
    | '/fiches/logique-booleenne'
    | '/fiches/pemdas'
    | '/fiches/tangente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fiches/$slug'
    | '/fiches/logique-booleenne'
    | '/fiches/pemdas'
    | '/fiches/tangente'
  id:
    | '__root__'
    | '/'
    | '/fiches/$slug'
    | '/fiches/logique-booleenne'
    | '/fiches/pemdas'
    | '/fiches/tangente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FichesSlugRoute: typeof FichesSlugRoute
  FichesLogiqueBooleenneRoute: typeof FichesLogiqueBooleenneRoute
  FichesPemdasRoute: typeof FichesPemdasRoute
  FichesTangenteRoute: typeof FichesTangenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiches/tangente': {
      id: '/fiches/tangente'
      path: '/fiches/tangente'
      fullPath: '/fiches/tangente'
      preLoaderRoute: typeof FichesTangenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiches/pemdas': {
      id: '/fiches/pemdas'
      path: '/fiches/pemdas'
      fullPath: '/fiches/pemdas'
      preLoaderRoute: typeof FichesPemdasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiches/logique-booleenne': {
      id: '/fiches/logique-booleenne'
      path: '/fiches/logique-booleenne'
      fullPath: '/fiches/logique-booleenne'
      preLoaderRoute: typeof FichesLogiqueBooleenneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiches/$slug': {
      id: '/fiches/$slug'
      path: '/fiches/$slug'
      fullPath: '/fiches/$slug'
      preLoaderRoute: typeof FichesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FichesSlugRoute: FichesSlugRoute,
  FichesLogiqueBooleenneRoute: FichesLogiqueBooleenneRoute,
  FichesPemdasRoute: FichesPemdasRoute,
  FichesTangenteRoute: FichesTangenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
